go-critic/go-critic

cmd/kfulint/main.go
lint/lint.go

- Embed command-line args into lint.Context.
- Use context more extensively in kfulint/main.go
Not sure that we need `PkgDir` inside `lint.Context`, but the main idea is:
- Flags that are only needed inside main (for global configuration) are not part of `lint.Context`.
- Flags that are useful for checkers are embedded into `lint.Context` and it doesn't know that they are "command-line flags" (because it may make sense to fill them directly, in tests for example).
Flags like `PkgDir` can be a part of `Flags` type, but it should be defined in `cmd/kfulint`, not in `lint` (because command-line args are a property of executable program, not library).

cmd/kfulint,lint: minor changes to PR #1

---

cmd/kfulint/main.go
lint/lint.go
lint/param-name_checker.go
lint/util.go
testdata/foo.go
testdata/foo_test.go

Also modify kfulint/main.go and lint.go to make
it possible to implement first checker.

lint: add param-name checker

---

cmd/kfulint/main.go
lint/type-guard_checker.go

Adding stub now to avoid `main.go` conflicts after other linters appear.
Will roll implementations in near future.

lint: add type-guard checker stub

---

testdata/foo_test.go
testdata/param-name/checker_tests.go
testdata/parenthesis/checker_tests.go

The structure will be: `testdata/${checker-name}/checker_tests.go`.
The package name for each test suite is `checher_test`. It doesn't matter right now though.
Discussion is possible. :)

testdata: move tests to separate dirs

---

cmd/kfulint/testdata/param-duplication/checker_tests.go

Added TODO cases, valid declarations that should not trigger warnings and tests for mixed arguments styles.

cmd/kfulint: add more param-duplication tests

---

cmd/kfulint/lint_test.go
cmd/kfulint/main.go
cmd/kfulint/testdata/_sanity/tests.go

This required to change dir-oriented approach to package-oriented.
kfulint now accepts package paths (well, import paths)
instead of directory paths.
Sanity tests are updated to import packages with fewer dependencies.
This helps to avoid big increase in test time.
(loader can be quite slow for packages with lots of imports.)
Fixes #54

cmd/kfulint: use loader package to read, parse and typecheck

---

cmd/kfulint/testdata/builtin-shadow/checker_tests.go
lint/builtin-shadow_checker.go

builtin-shadow_checker: add all predeclared identifiers

---

cmd/kfulint/testdata/builtin-shadow/checker_tests.go
lint/builtin-shadow_checker.go

builtin-shadow checker panics when assign stmt LHS
is not *ast.Ident.
This can be reproduced by running it over GOROOT using lintwalk.
This patch fixes an issue and adds tests that check that
this issue remains fixed.

lint: fix builtin-shadow checker panic

---

CONTRIBUTING.md

docs/contributing.md: add issues guide.

---

cmd/kfulint/testdata/ptr-to-ref-param/negative_tests.go
cmd/kfulint/testdata/ptr-to-ref-param/positive_tests.go
lint/lint.go
lint/ptr-to-ref-type-param_checker.go

Warn users when passing pointer to chan/map
```
func f(ch *chan string) (ch2 *chan *int) {
return nil
}
```

lint: do not use reference types in function parameters/results

---

cmd/kfulint/testdata/ptr-to-ref-param/positive_tests.go
lint/lint.go
lint/ptr-to-ref-param_checker.go

- Make checker type name (and filename) consistent with rule name
- Make referential type predicate function checker method.
Not every checker may want to define slice as referential type.
- s/ch/slice/ for parameter which is slice (to avoid confusion)
Also, I've made nickname typo in branch name. :3

lint: minor fixes to #146

---

cmd/lintwalk/main.go

Also changed usage from:
lintwalk -src-root=XYZ/src
to:
lintwalk XYZ/src
Since we only expect one project root, this is more convenient.
README already describes new usage.
Fixes #187

cmd/lintwalk: fix exec error

---

cmd/gocritic/testdata/flagDeref/positive_tests.go
cmd/gocritic/testdata/underef/positive_tests.go
lint/flagDeref_checker.go
lint/stddef_checker.go
lint/underef_checker.go
lint/wrappers.go

Also added tests for updated checkers to make sure
they do check global expressions now.
Fixes #124

lint: add global expr checker base

---

cmd/criticize/main.go
cmd/gocritic/main.go

Now printed like:
check-package: usage: [flags] package...
The "check-package" comes from gocritic log.SetPrefix.
This way, criticize binary does not need any knowledge
about sub-command names.
Fixes #191

cmd/criticize: update usage string

---

cmd/gocritic/testdata/switchif/negative_tests.go
lint/switchif_checker.go

lint/switchif: handle switch statements with multiple "case" values properly

---

lint/parenthesis_checker.go
lint/typeGuard_checker.go

I think this is how it supposed to be, right?
@cristaloleg

lint: use astp from go-toolsmith

---

docs/overview.md
lint/appendCombine_checker.go
lint/attributes.go
lint/builtinShadow_checker.go
lint/captLocal_checker.go
lint/docStub_checker.go
lint/elseif_checker.go
lint/flagDeref_checker.go
lint/lint.go
lint/longChain_checker.go
lint/paramTypeCombine_checker.go
lint/ptrToRefParam_checker.go
lint/rangeExprCopy_checker.go
lint/rangeValCopy_checker.go
lint/singleCaseSwitch_checker.go
lint/stdExpr_checker.go
lint/switchTrue_checker.go
lint/typeSwitchVar_checker.go
lint/typeUnparen_checker.go
lint/underef_checker.go
lint/unexportedCall_checker.go
lint/unnamedResult_checker.go
lint/unslice_checker.go
lint/unusedParam_checker.go

This makes passing empty ruleInfo not needed.
We retain type-safety and all benefits of "false" by
default of original approach.
Also mark unexportedCall as VeryOpinionated while there.

lint: re-design attribute passing to addChecker function

---

lint/appendCombine_checker.go
lint/wrappers.go

Also fixed incorrect wrapper name: s/wrapBlockChecker/wrapStmtListChecker/.
Fixes #249.

lint: re-organize wrappers.go

---

cmd/gocritic/testdata/captLocal/negative_tests.go
lint/checker_base.go

ast.Inspect caused to pass type expressions as names into
checker, leading to false positives for capitalized (exported) types.

lint: traverse params properly in wrapLocalNameChecker

---

cmd/gocritic/testdata/ptrToRefParam/negative_tests.go
lint/ptrToRefParam_checker.go

lint/ptrToRefParam: fix underlying types

---

cmd/criticize/main.go

Also skip VeryOpinionated checks for "all" (default) set.
Now we have this:
- Just "all" to include all stable checkers
- "all"+withOpinionated
- "all"+withExperimental
- "all"+withOpinionated+withExperimental
Should be enough for any sensible case, given that we
have explicit whitelist that permits any kind of checker.
Fixes #273

cmd/criticize: add withOpinionated and withExperimental flags

---

cmd/gocritic/testdata/importShadow/negative_tests.go
cmd/gocritic/testdata/importShadow/positive_tests.go
docs/overview.md
lint/importShadow_checker.go

Sometimes developers use the same name for the variables as imported packages, more often I see something like importing "log" package and having "log" variable in the code.
This linter checks what imports the package has and what variables got created and compares one to another.

add imported package names shadowing linter

---

docs/overview.md
docs/templates/overview.md.tmpl

This fixes issue with note section rendering.

docs/templates: move "notes" above "attrs" in overview tmpl

---

docs/overview.md
docs/templates/overview.md.tmpl

Merged experimental+stable checkers into single
template loop. It's a good thing to split table
into 2 parts, but there is no such need for the
document body. Removes code duplication and fixes
issue with duplicated notes (at least it seems that way).
Not "Fixes" because I'm not 100% sure issue is defeated.
Updates #295

cmd/makedocs: fix duplicated note sections

---

lint/docStub_checker.go
lint/ptrToRefParam_checker.go
lint/stdExpr_checker.go
lint/unexportedCall_checker.go
lint/unnamedResult_checker.go

docStub, stdExpr, unexportedCall and unnamedResult
are marked with experimental attirbute until they
are better tested and their bugs are fixed.
Updates #300

lint: mark 4 checkers as experimental

---

cmd/gocritic/testdata/typeUnparen/negative_tests.go
cmd/gocritic/testdata/typeUnparen/positive_tests.go
lint/internal/astwalk/type_expr_walker.go
lint/typeUnparen_checker.go

Handle (*T)(...) properly.
Added tests to make sure that #258 is resolved.
Updates #258

lint: improve type-expr walker and visitor

---

cmd/gocritic/testdata/unslice/negative_tests.go
cmd/gocritic/testdata/unslice/positive_tests.go
lint/unslice_checker.go

Previously handled only string slicing.
Now works for arbitrary slice types.

lint: handle any slices in unslice

---

cmd/criticize/main.go
cmd/lintwalk/main.go

```
/blah/path/to/goroot/src/pkg/file.go:1:2
=>
$GOROOT/src/pkg/file.go:1:1
Same for $GOPATH.
This behavior can be surpressed with `-shorterErrLocation=false` flag.
```

cmd/criticize: replace GOPATH and GOROOT err loc prefix

---

cmd/gocritic/testdata/_sanity/tests.go
cmd/gocritic/testdata/regexpMust/negative_tests.go
cmd/gocritic/testdata/regexpMust/positive_tests.go
docs/overview.md
lint/regexpMust_checker.go

At least for now, don't do same work as megacheck
and only suggest MustCompile|MustCompilePOSIX.
Fixes #209

lint: add regexpMust checker

---

lint/yodaStyleExpr_checker.go

- Use go-toolsmith version of astp.
- Add experimental + opinionated attrs.

lint: annotate yodaStylExpr with attrs + fix import

---

cmd/gocritic/testdata/docStub/negative_tests.go
cmd/gocritic/testdata/docStub/positive_tests.go
lint/docStub_checker.go

lint/docStub: do not check unexported funcs, warn about XXX

---

cmd/gocritic/testdata/appendAssign/negative_tests.go
cmd/gocritic/testdata/appendAssign/positive_tests.go
docs/overview.md
lint/appendAssign_checker.go

Detects suspicious assignments of append results.
Does recognize several popular slice/append idioms
to reduce the amount of false positives.
This kind of error may occur when append assignment being copy/pasted.

lint: add appendAssign checker

---

cmd/gocritic/testdata/elseif/negative_tests.go
lint/elseif_checker.go

Give up if there are any init stmt inside else-if chain.
Fixed #311

lint: handle init stmt inside if stmt properly in elseif checker

---

cmd/gocritic/testdata/namedConst/negative_tests.go
cmd/gocritic/testdata/namedConst/positive_tests.go
docs/overview.md
lint/namedConst_checker.go

Detects raw literal values that can be replaced
by already defined (and imported) named constant.
Fixes #215

lint: add namedConst checker

---

docs/overview.md
docs/templates/overview.md.tmpl

Now rendered page has proper title.
It was an issue with comment that surpressed correct expected
behavior. Moved it below the title.
Fixes #164

docs/templates/overview: optimize for github pages

---

docs/overview.md
lint/caseOrder_checker.go
lint/testdata/caseOrder/negative_tests.go
lint/testdata/caseOrder/positive_tests.go
lint/typeSwitchVar_checker.go
lint/util.go

Detects potential issues in switch statement case clauses order.
Fixes #362

lint: add caseOrder checker

---

README.md

We're using camelCase instead of dash-based convention now.

readme: update checker naming to reflect new convention

---

cmd/makedocs/main.go
docs/overview.md
lint/builtinShadow_checker.go
lint/docStub_checker.go
lint/importShadow_checker.go
lint/longChain_checker.go
lint/namedConst_checker.go
lint/nestingReduce_checker.go
lint/singleCaseSwitch_checker.go
lint/typeUnparen_checker.go
lint/unexportedCall_checker.go
lint/unslice_checker.go
lint/yodaStyleExpr_checker.go

Using gofmt to validate code snippets formatting.
Fixes #378

cmd/makedocs: check for doc comments formatting

---

lint/lint_test.go

lint_test.go imports path/filepath, so it's quite
uncomfortable to see filepath names here and there.
Renamed all of "filepath" names to "filename".

lint: fix import shadow complaints inside test runner

---

lint/indexOnlyLoop_checker.go
lint/testdata/indexOnlyLoop/negative_tests.go
lint/testdata/indexOnlyLoop/positive_tests.go
lint/util.go

Replaces usages of ast.Object with types.Object.

lint: use types.Object in indexOnlyLoop

---

lint/boolExprSimplify_checker.go
lint/dupSubExpr_checker.go
lint/testdata/boolExprSimplify/negative_tests.go
lint/testdata/boolExprSimplify/positive_tests.go
lint/util.go

```
Added rules include:
x > y || x == y => x >= y
x < y || x == y => x <= y
Plus their inverted lhs/rhs forms.
```

lint: teach boolExprSimplify to recognize combined comparisons

---

CONTRIBUTING.md

CONTRIBUTING.md: Register checker in `init()`

---

lint/testdata/underef/negative_tests.go
lint/testdata/underef/positive_tests.go
lint/underef_checker.go

Re-write 2 if statements with a single type switch.

lint: simplify underefChecker.checkStarExpr method

---

lint/hugeParam_checker.go
lint/rangeExprCopy_checker.go
lint/rangeValCopy_checker.go

Make hugeParam, rangeExprCopy, rangeValCopy checkers
sizeThreshold value configurable via config settings.
Default values remain unchanged.
Updates #477

lint: make sizeThreshold configurable

---

lint/elseif_checker.go
lint/testdata/elseif/negative_tests.go

Change default behavior not to warn on balanced statements.
A balanced if statement is a one where both branches
contain if statement, like in example below:
```go
if cond {
if x == 1 {
}
} else {
if x == 2 {
}
}
```
gocritic can be instructed to warn on these too by changing
skipBalanced value to false.
Fixes #420

lint: don't warn on balanced if-else in elseif checker

---

lint/testdata/underef/negative_tests.go
lint/testdata/underef/positive_tests.go
lint/underef_checker.go

By default, don't trigger (*v).method() if method
accpets receiver by pointer, since that may lead
to unwanted side-effects if method does mutate its receiver.
Fixes #520

lint: reduce underef checker false-positives rate

---

lint/sqlRowsClose_checker.go
lint/testdata/_sanity/tests.go

ctx.typeOf returns nil for some kinds of expressions.
Perform a nil check in sqlRowsClose to avoid panics.
Fixed #537

lint: fix panic in sqlRowsClose

---

docs/overview.md
lint/testdata/unlambda/.#negative_tests.go
lint/testdata/unlambda/negative_tests.go
lint/testdata/unlambda/positive_tests.go
lint/unlambda_checker.go

Detects function literals that can be replaced by a function/method value itself.
Fixes #550

lint: add unlambda checker

---

lint/floatCompare_checker.go
lint/testdata/floatCompare/negative_tests.go
lint/testdata/floatCompare/positive_tests.go

1. Fix print 'binaryExpr' as second argument
2. Add detection NaNCheckExpr: 'x != x' and InfCheckExpr: 'x + x == x'.
Result: less false-positives.

lint: update floatCompare checker

---

docs/manifest.md

This is required to reduce confusion and follow
some predictable path.
This is a draft.

docs/manifest: add project manifest doc

---

cmd/criticize/main.go
cmd/internal/flagparser/flag_parser.go
cmd/lintwalk/main.go

PR for #570
There is two commits, one is super simple and made required changes (enabled checkers controlled by config), second one add complexity and restrict to use config option together with "enable", "disable", etc. Some options that can control enabled checkers. 
This on my mind reduce complexity of support and made it more simple to use and understand.

config file control enabled checkers (#570)

---

lint/testdata/emptyFallthrough/negative_tests.go
lint/testdata/emptyFallthrough/positive_tests.go

Add some tests for nested switch-case-fallthrough statements
to prevent the checker logic to be simplified accidentally.
Harmonize tests.

lint: follow-up for PR566

---

docs/overview.md
lint/deprecatedComment_checker.go
lint/internal/astwalk/doc_comment_visitor.go
lint/internal/astwalk/visitor.go
lint/internal/astwalk/walker.go
lint/lint_private.go
lint/testdata/deprecatedComment/negative_tests.go
lint/testdata/deprecatedComment/positive_tests.go

Detects malformed deprecation comments.
When possible, suggests how to fix it.

lint: add deprecatedComment checker

---

lint/deprecatedComment_checker.go
lint/testdata/deprecatedComment/positive_tests.go

There is a big room for improvements, this implementation
is like a stub for further cases.

lint: handle simplest typos in deprecatedComment checker

---

lint/regexpMust_checker.go
lint/testdata/regexpMust/negative_tests.go

None false positives so far.
Implementation is trivial and there is almost no room for bugs.

lint: mark regexpMust as stable

---

lint/unusedParam_checker.go

We still need to make it less noisy when enabled.
Updates #516

lint: mark unusedParam as very opinionated

---

lint/all_checkers_test.go
lint/captLocal_checker.go

Only check params by default.
checkLocals=true enables previous behavior.
Tests are executed with checkLocals set to true.
Updates #530
Fixes #526

lint: don't check locals in captLocal by default

---

cmd/criticize/main.go
lint/all_checkers_test.go
lint/lint.go

Move file-related resource loading into Context.SetFileInfo.
This way, integrating code can resolve these Context.require
fields before running checkers concurrently.
Fixes #617

lint: fix concurrent map write in Checker.Check(file)

---

lint/longChain_checker.go

Make it easier to avoid using it for the users that
do provide -withExperimental flag.
If not proven to be useful or fixable, should be
removed completely in near time.
Updates #445

lint: mark longChain as opinionated (temporary solution)

---

lint/blankParam_checker.go

It's OK to use "unused" inside docs and comments.
Only checker name was an issue.

lint: follow-up for #636

---

lint/commentedOutCode_checker.go
lint/testdata/commentedOutCode/negative_tests.go

Skip ast.CallExpr something looks like a function call, but there
is an extra whitespace between a callable expression and
parameter list.

lint: fix commentedOutCode handling of "f ()"

---

lint/appendAssign_checker.go
lint/lint.go
lint/lint_private.go
lint/rangeExprCopy_checker.go
lint/rangeValCopy_checker.go

Updates #459
We still need to reflect this attr in docs (overview.md) and add relevant flags for gocritic cmd.

lint: introduce performance attribute

---

docs/overview.md
lint/assignOp_checker.go
lint/boolExprSimplify_checker.go
lint/dupSubExpr_checker.go
lint/indexAlloc_checker.go
lint/nilValReturn_checker.go
lint/testdata/indexAlloc/negative_tests.go
lint/testdata/indexAlloc/positive_tests.go
lint/util.go

Performance check.
Suggests to replace strings.Index with bytes.Index
where it can make code more efficient.
See golang/go#25864

 lint: add indexAlloc checker

---

docs/overview.md
lint/nilValReturn_checker.go

closes #656 
@Quasilyte I fixed the typo by updating the `docs/overview.md` and generated the docs using -
```cd cmd/makedocs && go run main.go``` It generated --
```
if err != nil {
return nil
}
```
I had to update this to return `err` manually. Do we have to update any other file?

#656 Fix typo & generate docs

---

lint/testdata/appendAssign/negative_tests.go
lint/testdata/appendAssign/positive_tests.go
lint/testdata/boolExprSimplify/negative_tests.go
lint/testdata/boolExprSimplify/positive_tests.go
lint/testdata/commentedOutCode/negative_tests.go
lint/testdata/commentedOutCode/positive_tests.go
lint/testdata/deadCodeAfterLogFatal/negative_tests.go
lint/testdata/deadCodeAfterLogFatal/positive_tests.go
lint/testdata/dupCase/negative_tests.go
lint/testdata/dupCase/positive_tests.go
lint/testdata/emptyFallthrough/negative_tests.go
lint/testdata/emptyFallthrough/positive_tests.go
lint/testdata/evalOrder/negative_tests.go
lint/testdata/evalOrder/positive_tests.go
lint/testdata/indexAlloc/negative_tests.go
lint/testdata/indexAlloc/positive_tests.go
lint/testdata/namedConst/negative_tests.go
lint/testdata/namedConst/positive_tests.go
lint/testdata/regexpMust/negative_tests.go
lint/testdata/regexpMust/positive_tests.go
lint/testdata/sqlRowsClose/negative_tests.go
lint/testdata/sqlRowsClose/positive_tests.go
lint/testdata/underef/negative_tests.go
lint/testdata/underef/positive_tests.go

I have renamed package checker_tests into checker_test. Now, It has resulted as below.
```
$ grep -nr 'package checker_test$' | wc -l
115
$ grep -nr 'package checker_tests$' | wc -l
0
```

#669 renames package name from checker_tests into checker_test

---

lint/appendAssign_checker.go

lint: remove "performance" attr from appendAssignChecker
fix #685

lint: remove "performance" attr from appendAssignChecker

---

lint/testdata/typeSwitchVar/negative_tests.go

I've added some negative tests to typeSwitchVar.
The issue: https://github.com/go-critic/go-critic/issues/684

lint: add negative tests to typeSwitchVar

---

lint/testdata/typeUnparen/negative_tests.go
lint/unlambda_checker.go

searched all files with grep - regex: ^\s*$\s*}

* removed all redundant newlines before `}` Issue: #698

---

checkers/commentFormatting_checker.go
checkers/testdata/_integration/check_main_only/linttest.golden
checkers/testdata/_integration/check_main_only/main.go
checkers/testdata/commentFormatting/negative_tests.go
checkers/testdata/commentFormatting/positive_tests.go

Detects comments like this:
```
//this is a comment without a leading space
```
Suggested fix is:
```
// this is a comment with a leading space
```
Fixes #469
Updates #470

checkers: add commentFormatting checker

---

checkers/methodExprCall_checker.go
checkers/testdata/methodExprCall/negative_tests.go
checkers/testdata/methodExprCall/positive_tests.go

Also simplify implementation by using typep.IsTypeExpr.
Fixes #681

checkers: fix methodExprCall false positives

---

checkers/flagName_checker.go
checkers/importShadow_checker.go
checkers/testdata/_importable/flag/flag.go
checkers/testdata/flagName/negative_tests2.go
checkers/utils.go

Verify that "flag.Xxx" function comes from the standard
library, not from just any package that is called flag and
happen to have something like Bool or Int8 function that
look like something from the standard flag package.
Move stdlib pkg check to utils.go and use that in
importShadow checker as well.
Fixes #734

checkers: fix panic in flagName

---

checkers/boolExprSimplify_checker.go

Don't copy AST expressions those type is not bool.
We still do a lot of copying, but at least it's only
performed for boolean-typed expressions.
Refs #493

checkers: avoid eager copy in boolExprSimplify

---

checkers/boolExprSimplify_checker.go
checkers/testdata/boolExprSimplify/negative_tests.go

This fixes a bug in boolExprSimplify checker.
Fixes #673

checkers: don't do invertComparison for floats

---

checkers/equalFold_checker.go
checkers/testdata/equalFold/negative_tests.go
checkers/testdata/equalFold/positive_tests.go

Handle bytes comparisons in addition to strings comparisons.
Also fix a bug that made linter suggest invalid replacements.
It happened because we haven't checked which call is under
callX and callY. If there is something that is not ToUpper
or ToLower, we should not simplify a call to its first argument.
In addition, add negative tests.

checkers: extend equalFold checker to bytes.EqualFold

---

checkers/utils.go

`isStdlibPkg` now checks the argument for nil (built-in types don't have a package).
Fixes #749

checkers: fix nil pointer dereference in flagName

---

checkers/commentFormatting_checker.go
checkers/testdata/commentFormatting/negative_tests.go

checkers: recognize //line and //nolint in commentFormatting

---

checkers/boolExprSimplify_checker.go
checkers/testdata/boolExprSimplify/negative_tests.go
checkers/testdata/boolExprSimplify/positive_tests.go

New patterns:
`x > c && x < c+2` => `x == c+1`
`x >= c && x < c+1` => `x == c`
`x > c && x <= c+1` => `x == c+1`
`x >= c && x <= c` => `x == c`
`x < c || x > c` => `x != c`
`x <= c || x > c+1` => `x != c+1`
`x < c || x >= c+1` => `x != c`
`x <= c || x >= c+2` => `x != c+1`
Updates #616

checkers: add new patterns to boolExprSimplify

---

checkers/stringXbytes_checker.go

- Use "style" tag instead of "diagnostic"
- Use byteCast.Args[0] instead of strings woodoo

checkers: followup for #773

---

checkers/flagName_checker.go
checkers/testdata/flagName/negative_tests.go

The main problem came from the flagName trying
to check method calls while it should only handle
function calls.
Fixes #784.

checkers: proper pkg/obj check for flagName

---

checkers/equalFold_checker.go
checkers/testdata/equalFold/negative_tests.go

The following code makes sense and is correct:
strings.ToLower(x) == x
Previously, equalFold would trigger on that.
Added a check that upper/lower casing call
operand is not the same as LHS/RHS.

checkers: fix equalFold false positive

---

docs/overview.md
docs/templates/checker.partial.tmpl

The problem was caused by checker params list
that included (for some reason) the next header.
To avoid whitespace-driven decisions, use
HTML elements to emit lists, so they are closed
before next checker heading starts.
Also added octalLiteral checker docs.
Fixes #802

cmd/makedocs: fix headers formatting

---

checkers/internal/lintutil/zero_value.go
checkers/newDeref_checker.go
checkers/testdata/_importable/examplepkg/examplepkg.go
checkers/testdata/_integration/check_main_only/linttest.golden
checkers/testdata/_integration/check_main_only/main.go
checkers/testdata/newDeref/negative_tests.go
checkers/testdata/newDeref/positive_tests.go

Finds *new(T) expressions and suggests to simplify them
by using T zero value instead.
For example:
*new(string) => ""
*new(bool)   => false
*new(myInt)  => myInt(0)

checkers: add newDeref checker

---

checkers/caseOrder_checker.go
checkers/testdata/caseOrder/positive_tests.go

caseOrder: error: runtime error: invalid memory address or nil pointer dereference

---

checkers/dupImports_checker.go
checkers/testdata/dupImports/negative_tests.go
checkers/testdata/dupImports/positive_tests.go

Am proposing a new "style" checker that verifies that you are not importing the same package twice in the same Go file under different aliases.
This is not using one of the `astwalk.WalkerFor*` interfaces (which are proxies for `lintpack.FileWalker`) as those do not give access to a file's imports. Instead it directly reimplements the `lintpack.FileWalker` interface itself.
Have added the required positive and negative test files as well.
Example output:
```text
 -> gocritic check -enable=dupImports checkers/testdata/dupImports/positive_tests.go
./checkers/testdata/dupImports/positive_tests.go:4:8: dupImports: package is imported 3 times under different aliases on lines 4, 8 and 10
./checkers/testdata/dupImports/positive_tests.go:8:2: dupImports: package is imported 3 times under …
```

New dupImports checker

---

checkers/testdata/wrapperFunc/negative_tests.go
checkers/testdata/wrapperFunc/positive_tests.go
checkers/wrapperFunc_checker.go

Suggest changing SplitN(a, b, -1) to Split(a, b).

checkers: teach wrappedFunc to handle SplitN

---

checkers/rangeValCopy_checker.go
checkers/typeSwitchVar_checker.go
naming_conventions.json

Also add a rule for ctxt->ctx renaming.

checkers: fix go-namecheck complaints

---

checkers/evalOrder_checker.go
checkers/testdata/evalOrder/negative_tests.go
checkers/testdata/evalOrder/positive_tests.go

Checks for return statements that may have unwanted
dependency on the evaluation order.
See:
https://github.com/golang/go/issues/27098
https://github.com/golang/go/issues/23188

checkers: add evalOrder checker

---

checkers/commentedOutCode_checker.go
checkers/testdata/commentedOutCode/negative_tests.go

For some reason tests passed well, but `gocritic check -enable commentedOutCode fmt` returns.
```
$GOROOT/src/fmt/example_test.go:242:2: commentedOutCode: may want to remove commented-out code
$GOROOT/src/fmt/example_test.go:275:2: commentedOutCode: may want to remove commented-out code
$GOROOT/src/fmt/gostringer_example_test.go:56:2: commentedOutCode: may want to remove commented-out code
```
P.S lines are from found warnings.

lint: commentedOutCode add false positives tests

---

checkers/boolExprSimplify_checker.go
checkers/testdata/boolExprSimplify/negative_tests.go

Don't apply fold ranges in boolExprSimplify for float operands.
Fixes #848

checkers: fix fold-ranges for floats in boolExprSimplify

---

checkers/commentedOutCode_checker.go
checkers/testdata/commentedOutCode/negative_tests.go
checkers/utils.go

Recognize "Output:" comment inside example tests.
Fixes #851

checkers: fix "Output:" false positive in commentedOutCode

---

.travis.yml

add to the CI master so that it's always possible to check that go-critic is ready for the next go

build for master as well

---

checkers/regexpPattern_checker.go
checkers/testdata/regexpPattern/negative_tests.go
checkers/testdata/regexpPattern/positive_tests.go

Currently only checks whether the pattern contains
an unescaped "." near known top level domain.
So, `google.com` is probably flawed and
`google\.com` is considered to be correct.
It's not a security issue most of the time, but
it's better to keep that surface as thin as possible
to avoid potential problems.

add regexpPattern checker

---

checkers/dupArg_checker.go
checkers/testdata/dupArg/negative_tests.go

The dupArg checker assumes "copy" has at least two arguments. Builtins can be redefined though, so this assumption may not be true!
Fixes #870.

checkers: fix panic on shadowing "copy" builtin

---

checkers/testdata/truncateCmp/negative_tests.go
checkers/testdata/truncateCmp/positive_tests.go
checkers/truncateCmp_checker.go

Checks when numeric types are compared with truncated conversion on
the either side.
Problematic code example:
```
func f(x int32, y int16) bool {
return int16(x) < y
}
```
Fixed code example:
```
func f(x int32, int16) bool {
return x < int32(y)
}
```
See https://github.com/golang/go/issues/35010

checkers: add truncateCmp checker

---

checkers/testdata/truncateCmp/negative_tests.go
checkers/truncateCmp_checker.go

To avoid false positives, don't warn on comparisons
where both sides have integer conversions.

checkers: don't warn on expressions with 2 casts

---

.gitignore
Makefile
README.md

I felt this as friction when following the installation steps in README.md, so I thought I'd simplify it a bit.

Add make target for gocritic binary

---

checkers/testdata/whyNoLint/negative_tests.go
checkers/testdata/whyNoLint/positive_tests.go
checkers/whyNoLint_checker.go

This checker inspects machine-readable //nolint comments (per the
conventions from https://github.com/golangci/golangci-lint#nolint) to
ensure that they are accompanied by human-readable explanatory
comments on the same line.
The intention is to enable teams to enforce a policy of not disabling
linters without providing an explicit justification.

Add whyNoLint checker.

---

Makefile

* Correct linter.version argument in `Makefile`.
After `make gocritic` I get wrong version in output of `gocritic version` - `v0.3.4`, correct is `v0.4.0`.

makefile: correct linter.version argument

---

checkers/testdata/_integration/check_main_only/main.go

They were failing due to the lack of unlambda warning.
It happened because the code used a closure (var-assigned func)
instead of a normal func. We don't warn on closures
anymore (see #888), so that warning disappeared.
For whatever reason, CI passed and we didn't notice it.
Maybe integration tests are not executed as a part of our pipeline?
Anyway, tests should be fixed now.

checkers: fix integration tests

---

checkers/mapKey_checker.go
checkers/testdata/mapKey/negative_tests.go
checkers/testdata/mapKey/positive_tests.go

Detects suspicious whitespace inside map literal keys.
Detects duplicated map keys that are not basic literals.
Basic literals are handled by Go compiler.

checkers: add mapKey checker

---

checkers/deferAtTheEnd_checker.go
checkers/exitAfterDefer_checker.go
checkers/testdata/deferAtTheEnd/negative_tests.go
checkers/testdata/deferAtTheEnd/positive_tests.go

Detects uneeded defer at the end of function.

checker: add defer at the end of function checker

---

checkers/testdata/wrapperFunc/negative_tests.go
checkers/testdata/wrapperFunc/positive_tests.go
checkers/wrapperFunc_checker.go

add draw.Draw to draw.DrawMask checker

---

checkers/commentFormatting_checker.go
checkers/testdata/commentFormatting/negative_tests.go

Similar to this change https://github.com/go-critic/go-critic/pull/756/files
but support for `go:generate`

feat: allow go:generate directives

---

README.md

We don't use TravisCI anymore => its badge should be removed.

readme: use GitHub actions badge

---

checkers/badRegexp_checker.go

checkers: reduce state size from 256 to 128 bytes.

---

checkers/badRegexp_checker.go
checkers/testdata/badRegexp/positive_tests.go

It seems to be more complicated that just mapping it to a final position.
Reverting this part of anchors check until a better understanding is gained.

checkers: revert "redundant $" check

---

checkers/regexpSimplify_checker.go
checkers/testdata/regexpSimplify/negative_tests.go
checkers/testdata/regexpSimplify/positive_tests.go

Handles simplest common suffixes and prefixes.

checkers: add prefix/suffix factoring in regexpSimplify

---

checkers/testdata/unnecessaryDefer/negative_tests.go
checkers/unnecessaryDefer_checker.go
go.sum

By keeping track of the block type we can differentiate between
functions and other blocks. This way we can enure that only blocks
ending with explicit return or end of functions yelds warnings.

Fix false positives for unnecessaryDefer. #926

---

checkers/commentFormatting_checker.go

Make it clear that comments like "go:generate" are examples
and are not actual compiler directives.

checkers: fix Go warning

---

checkers/filepathJoin_checker.go
checkers/testdata/filepathJoin/negative_tests.go
checkers/testdata/filepathJoin/positive_tests.go

```
Reports filepath.Join() string literal arguments that contain
'/' or '\' as it kinda defeats the purpose of using that function.
```

checkers: add filepath.Join checker

---

checkers/sloppyTypeAssert_checker.go
checkers/testdata/sloppyTypeAssert/negative_tests.go
checkers/testdata/sloppyTypeAssert/positive_tests.go

```
Reports interface->interface type assertions that may be redundant.
- Any type assertion to interface{} is redundant
- Any I->I (identical) type assertion is redundant
- I1->I2 assertion is redundant if I1 implements I2
```

checkers: add sloppyTypeAssert checker

---

checkers/sqlQuery_checker.go
checkers/testdata/sqlQuery/negative_tests.go
checkers/testdata/sqlQuery/positive_tests.go

Reports `_, err := db.Query()` pattern.
Suggests to use Exec() instead of Query in this case.

checkers: add sqlQuery checker

---

checkers/sortSlice_checker.go
checkers/testdata/sortSlice/negative_tests.go
checkers/testdata/sortSlice/positive_tests.go
go.mod
go.sum

Find suspicious sort slice calls.
Sorting `slice` argument with a callback that uses
another slice is usually incorrect, as only one
slice will be modified by Slice call inplace.

checkers: add sortSlice checker

---

checkers/sqlQuery_checker.go
checkers/testdata/sqlQuery/negative_tests.go

If astcast to SelectorExpr failed, funcExpr.Sel will be nil.
Bug reported by @un000

checkers: fix sqlQuery panic

---

checkers/testdata/unnecessaryDefer/negative_tests.go
checkers/testdata/unnecessaryDefer/positive_tests.go
checkers/unnecessaryDefer_checker.go

If return results contain something that is not a constant
expression, do not emit a warning.
Fixes #941

checkers: restrict unnecessaryDefer to const expr only

---

checkers/singleCaseSwitch_checker.go
checkers/testdata/singleCaseSwitch/negative_tests.go
checkers/testdata/singleCaseSwitch/positive_tests.go

If we re-write switch to an if, break statements may become an issue.
To avoid false positives, singleCaseSwitch checker won't report
switch statements of 1 case if it contains a break statement
(unless that statement is inside for/select/switch itself.)
Fixes #682

checkers: don't warn on single case if it contains a break

---

checkers/sloppyTypeAssert_checker.go
framework/linter/lintpack.go

Used a new method in sloppyTypeAssert checker to avoid explicit
nil checks and nil deref panics together.
The next step is to replace all ctx.TypesInfo.TypeOf() calls with ctx.TypeOf().
Fixes #955

framework/linter: add nil-safe TypeOf method

---

framework/lintmain/internal/check/check.go

When doing packages Load(), we need to pass a packages.NeedName flag,
so our pkgload package can categorize the packages correctly.

framework/lintmain/internal/check: add missing NeedName mode flag

---

checkers/builtinShadowDecl_checker.go
checkers/builtinShadow_checker.go
checkers/testdata/builtinShadowDecl/negative_tests.go
checkers/testdata/builtinShadowDecl/positive_tests.go

Finds top-level symbols that have a name that will shadow a
builtin identifier for the entire package.
Unlike builtinShadow, it's not a style but rather a diganostic check.
Fixes #868

checkers: add builtinShadowDecl

---

framework/linttest/integration.go

Pass -race flag to the go build command when building
a test go-critic binary.

framework/linttest: enable -race for intergration tests

---

framework/linttest/integration.go

framework/linttest: allow trailing \n in golden files

---

checkers/exitAfterDefer_checker.go
checkers/testdata/_integration/check_main_only/linttest.golden
checkers/testdata/exitAfterDefer/positive_tests.go

Clarifies the verbiage that the `exitAfterDefer` rule uses to warn the user to improve clarification as to the issue and consequences

Clarifies exitAfterDefer warning verbaige

---

checkers/checkers_test.go
checkers/testdata/commentFormatting/negative_tests.go
checkers/testdata/filepathJoin/negative_tests.go
checkers/testdata/octalLiteral/negative_tests.go
checkers/testdata/octalLiteral/positive_tests.go
checkers/testdata/regexpPattern/negative_tests.go
framework/linttest/linttest.go

If a package loaded from the testdata contains errors,
fail the test unless there is an entry in IgnoreErrors slice
that asks the linttest to skip error checking for that checker.
Fixes #977

framework/linttest: fail on pkg errors by default

---

checkers/exitAfterDefer_checker.go
checkers/testdata/exitAfterDefer/negative_tests.go

We allow `defer os.Exit()` calls
as it's harder to determine whether they're going
to clutter anything without actually trying to
simulate the defer stack + understanding the control flow.
Fixes #995

checkers: ignore `defer exit()` in exitAfterDefer

---

checkers/exitAfterDefer_checker.go

checkers: remove redundant cond in exitAfterDefer

---

checkers/badLock_checker.go
checkers/testdata/badLock/negative_tests.go
checkers/testdata/badLock/positive_tests.go

Finds mismatching Lock+Unlock sequences.
Lock+RUnlock -> error
RLock+Unlock -> error
Lock+Unlock -> OK
RLock+RUnlock -> OK
It only checks the 2 adjusted statements.
We don't check for types being sync.Mutex or sync.RWMutex,
let's see how bad it will be for a false positive rates.
People could embed locks or implement custom Lock+Unlock methods.
We won't mark this checker as stable until it's properly tested,
so it shouldn't be a deal breaker.

checkers: add badLock checker

---

checkers/flagName_checker.go
checkers/testdata/flagName/negative_tests.go
checkers/testdata/flagName/positive_tests.go

From the https://github.com/golang/go/issues/41792
And these are invalid flag names:
* Empty String:
* If the flag name is an empty string and is used in the `-flag x` form, the flag starting with hyphen('-''') can be the non-flag argument and the flag starting with double hyphen('--''') can be the terminator.
* > Flag parsing stops just before the first non-flag argument("-" is a non-flag argument) or after the terminator "--".
* Starting with hyphen:
* According to the document the flag should start with '-' or '--'. But, if the flag name starts with hyphen, this package can’t distinguish between '-''-flag' and '--''flag'.
* Containing equal sign:
* This package uses equal sign to split the flag into a name-value pair. So, if the flag name contains equal sign, this package can't split …

checkers: extend flagName diagnostics

---

checkers/ruleguard_checker.go
checkers/testdata/_integration/ruleguard-glob/file.go
checkers/testdata/_integration/ruleguard-glob/linttest.golden
checkers/testdata/_integration/ruleguard-glob/linttest.params
checkers/testdata/_integration/ruleguard-glob/rules1.go
checkers/testdata/_integration/ruleguard-glob/rules2.go

Currently the list of ruleguard files is specified as a comma-separated list.
This PR allows to specify a pattern (using filepath.Glob).
Is there a way to add unit tests for this?
Also, not sure how to document the Match pattern: https://golang.org/pkg/path/filepath/#Match

Add support for glob pattern in ruleguard/rules configuration

---

rulestest/rules_test.go
rulestest/testdata/checkers/badChecker.go
rulestest/testdata/checkers/contextStub.go

Instead of using a real `framework.Context` I had to use a
stub struct, see https://github.com/golang/go/issues/37054

add rulestest to test our rules.go file

---

go.mod
go.sum

upgrade ruleguard to 0.3.2

---

checkers/appendAssign_checker.go
checkers/testdata/appendAssign/negative_tests.go
checkers/testdata/appendAssign/positive_tests.go

Makes the `appendAssign` checker also warn on a short declaration, not just on assignments, e.g.
```go
x := []int{}
y := append(x, 1) // <- bad!
```
The motivation for this restriction is that allowing short declarations is error prone: https://blog.allegro.tech/2017/07/golang-slices-gotcha.html
Additional context: https://stackoverflow.com/a/35276346

Fix appendAssign checker to also warn on short decl

---

checkers/preferDecodeRune_checker.go
checkers/testdata/preferDecodeRune/negative_tests.go
checkers/testdata/preferDecodeRune/positive_tests.go

This PR adds a simple checker to find `[]rune("abc")[0]` and suggest `utf8.DecodeRuneInString("abc")`. 
Expressions like 
```go
[]rune("abc")[0]
```
causes unnecessary rune slice allocation.
See https://github.com/golang/go/issues/45260.

Add `preferDecodeRune`

---

checkers/deferUnlambda_checker.go

Fixed the `deferUnlambda` checker's `After` documentation string `f()`->`defer f()`, to indicate the checker doesn't expect the removal of the defer statement, only expects to transform the lambda wrapped function call into a simple function call.
This is in line with the current functionality which [expects](https://github.com/go-critic/go-critic/blob/6090d88757f445be96d2e507d7b17e2abcb40c4b/checkers/deferUnlambda_checker.go#L93) the corrected code to look like `defer f()`.

Fixed deferUnlambda `After` docs `f()`->`defer f()`

---

checkers/octalLiteral_checker.go
checkers/testdata/octalLiteral/negative_tests.go

checkers/octalLiteral: skip check for fs package

---

checkers/commentFormatting_checker.go
checkers/testdata/commentFormatting/negative_tests.go

This change will allow comments used a vertical line
such as
```
///////////
//--------
//++++++++
//########
```
Fixes: https://github.com/go-critic/go-critic/issues/1065

commentFormatting: should allow vertical bars

---

checkers/commentFormatting_checker.go

Used by some versions of GoLand and friends IDE's.

checkers(commentFormatting): treat //noinspection as pragma

---

checkers/rules/rules.go
checkers/rulesdata/rulesdata.go

Removed a typo from a `Suggest()` string.

checkers: fix equalFold rules autofix templates

---

checkers/boolExprSimplify_checker.go
checkers/commentFormatting_checker.go
checkers/ruleguard_checker.go

PR for: https://github.com/go-critic/go-critic/issues/1176

Add ignore flag

---

framework/lintmain/internal/check/check.go
framework/linttest/linttest.go
go.mod
go.sum

Also updated pkgload library version.

cmd/gocritic: add -cpuprofile and -memprofile flags

---

checkers/checkers.go
checkers/embedded_rules.go

Move out embedded rules from checkers/checkers.go to checkers/embedded_rules.go
Issue: https://github.com/go-critic/go-critic/issues/1177

Move out embedded rules from checkers/checkers.go

---

checkers/internal/lintutil/astfind.go
checkers/testdata/unlabelStmt/negative_tests.go
checkers/typeSwitchVar_checker.go
checkers/unlabelStmt_checker.go

.. in nested for loops
this fixes issue #1130 and adds a test for it

ignore labeled continue in select statement

---

checkers/deprecatedComment_checker.go
checkers/testdata/deprecatedComment/negative_tests.go
checkers/testdata/deprecatedComment/positive_tests.go

pr for: https://github.com/go-critic/go-critic/issues/1183
benchmarks in progress

optimize deprecatedComment_checker: delete regexp usage

---

checkers/commentFormatting_checker.go

checkers: optimize commentFormatting

---

checkers/commentFormatting_checker.go

checkers: add fixable for commentFormatting (#1190)

---

README.md

Document that the security tag is disabled by default. Also document
that there are currently no checks in the security tag, so enabling it
will fail.
$ ./gocritic check -v -enable='#security
init checkers: empty checkers set selected
$ echo $?
1
When trying to enable the tag through golangci-lint, this is the error:
ERRO Invalid gocritic settings: gocritic [enabled]tag "security" doesn't
exist
The tag was added in #989.
Signed-off-by: Daniel Farrell <dfarrell@redhat.com>

README.md: Doc sec tag disabled, fails if enabled

---

framework/lintmain/internal/check/check.go
go.mod
go.sum

all: drop bright package

---

checkers/ruleguard_checker.go
checkers/testdata/_integration/ruleguard/f1.go
checkers/testdata/_integration/ruleguard/linttest.golden
checkers/testdata/_integration/ruleguard/linttest.golden2
checkers/testdata/_integration/ruleguard/linttest.golden4
checkers/testdata/_integration/ruleguard/linttest.params
checkers/testdata/_integration/ruleguard/rules.go

skip experimental tag by default for user defined rules

---

checkers/embedded_rules.go
cmd/gocritic/main.go

The `checkers` package user should use `checkers.InitEmbeddedRules()`
if ruleguard-based rules should be enabled.
Fixes #1218

checkers: turn `init()` for embedded rules into exported func

---

checkers/hugeParam_checker.go
checkers/rangeValCopy_checker.go
checkers/testdata/hugeParam/negative_tests_go118.go
checkers/testdata/rangeValCopy/negative_tests_go118.go
go.mod

StdSizes.SizeOf method doesn't support type parameters. https://github.com/golang/go/blob/78b722d8c2f764c3048c6f0344e9ebcd2687813d/src/go/types/sizes.go#L156-L159
Fixes go-critic/go-critic#1223

don't call SizeOf for type parameters

---

checkers/paramTypeCombine_checker.go
checkers/testdata/paramTypeCombine/negative_tests_go118.go
checkers/testdata/paramTypeCombine/positive_tests_go118.go
checkers/testdata/typeDefFirst/negative_tests_go118.go
checkers/testdata/typeDefFirst/positive_tests_go118.go
checkers/typeDefFirst_checker.go
go.mod

Fixes go-critic/go-critic#1193

supported generics for typeDefFirst and paramTypeCombine

---

checkers/hugeParam_checker.go
checkers/rangeExprCopy_checker.go
checkers/rangeValCopy_checker.go
checkers/truncateCmp_checker.go
framework/linter/linter.go
rules.go

Also add a ruleguard rule to avoid the unwanted sizeof form
in the future.

checkers: use ctx.SizeOf instead of SizesInfo.SizeOf

---

checkers/embedded_rules.go
cmd/gocritic/main.go

Related to #1246 and #1218.
Inside golangci-lint, we have to catch the panic with a `recover`.
It's more API friendly if the function `InitEmbeddedRules` returns an error.

feat(InitEmbeddedRules): return an error instead of panic

---

README.md

As of go 1.18 `go get` outside of a module is deprecated, we should use `go install` instead. 
This PR adds a small note on this for new users who wish to download go-critic

docs: update README install instruction for go 1.18

---

checkers/checkers_test.go
checkers/rules/rules.go
checkers/rulesdata/rulesdata.go
checkers/testdata/redundantSprint/negative_tests.go

Also enable embedded rules testing: we need to call
InitEmbeddedRules() somewhere inside the testing code
in order for them to be registered.
Fixes #1255

checkers: fix reflect.Value suggestion in redundantSprint

---

go.mod
go.sum

Both packages have improved generics support now.

deps: update astequal and astcopy packages

---

checkers/newDeref_checker.go
checkers/testdata/newDeref/negative_tests118.go

fix(newDeref): ignore generics

---

checkers/badRegexp_checker.go
checkers/testdata/badRegexp/positive_tests.go

fix(badRegexp): use stable sort

---

checkers/analyzer/run.go
checkers/ruleguard_checker.go
framework/linter/linter.go
framework/lintmain/internal/check/check.go
framework/linttest/linttest.go

add new warn method without ast.Node usage: https://github.com/go-critic/go-critic/pull/1276

add new method for ruleguard warnings

---

cmd/gocritic/check.go

cmd/gocritic: use checkGenerated flag properly

---

checkers/octalLiteral_checker.go

This PR changes the `octalLiteral` check to show a warning only if the Go version is greater than 1.13. Because prefixes `0o` or `0O` are available since [Go 1.13](https://go.dev/doc/go1.13).
- Clone https://github.com/golang/dl. This repo targets [Go 1.11.](https://github.com/golang/dl/blob/c7dbe52702e1669c6f0ad1f36e68d6e0864a1c5d/go.mod#L3)
- Run `gocritic check -go 1.11 -enable octalLiteral ./...`
No warnings.
There are warnings:
```
./internal/genv/main.go:60:45: octalLiteral: use new octal literal style, 0o755
./internal/genv/main.go:63:49: octalLiteral: use new octal literal style, 0o666
./internal/version/gotip.go:71:31: octalLiteral: use new octal literal style, 0o755
./internal/version/version.go:109:35: octalLiteral: use new octal literal style, 0o755 …
```

checkers/octalLiteral: should warn only for Go >= 1.13

---

checkers/embedded_rules.go

This PR fixes a bug when `-go` flag is ignored by `gocritic`.
Run the following:
```
gocritic check -enable syncMapLoadAndDelete -go 1.14 checkers/testdata/syncMapLoadAndDelete/positive_tests.go
```
[sync#Map.LoadAndDelete](https://pkg.go.dev/sync#Map.LoadAndDelete) added in Go 1.15. So, there should not be any warnings for Go 1.14.
There is a warning:
```
./checkers/testdata/syncMapLoadAndDelete/positive_tests.go:10:3: syncMapLoadAndDelete: use m.LoadAndDelete to perform load+delete operations atomically
```
---
There should be an integration test for this situation but I don't know where to add it.

checkers: fix setting of Go version for ruleguard

---

checkers/analyzer/run.go
checkers/internal/lintutil/astflow.go
checkers/mapKey_checker.go
checkers/testdata/builtinShadow/negative_tests.go
checkers/testdata/commentFormatting/positive_tests.go
checkers/testdata/dynamicFmtString/positive_tests.go
checkers/testdata/evalOrder/positive_tests.go
checkers/testdata/mapKey/positive_tests.go
checkers/testdata/rangeValCopy/positive_tests.go
checkers/utils.go

This PR fixes typos in the warning message, comments, and testdata function names.

checkers: fix typos

---

checkers/rules/rules.go
checkers/rulesdata/rulesdata.go
checkers/testdata/externalErrorReassign/positive_tests.go
docs/overview.md

This PR corrects a typo in the description of the checker `externalErrorReassign`.

checkers: fix typo in externalErrorReassign description

---

checkers/checkers_test.go
checkers/commentedOutCode_checker.go
checkers/testdata/commentedOutCode/negative_tests.go
checkers/testdata/commentedOutCode/positive_tests.go
docs/overview.md

checkers/commentedOutCode: add minimum length of comment parameter.

---

checkers/hugeParam_checker.go
checkers/testdata/hugeParam/negative_tests.go

checkers/hugeParam: ignore method String() string.

---

.github/workflows/doc.yaml

Autogenerate of doc into ci/cd
<details>
<summary>Simple diagram</summary>
</details>
Need to add token into secrets.
In my case, tested on fine-grained personal access token with perms:
1. Read access to administration and metadata.
2. Read and Write access to code.
Close #1016
Related: https://github.com/go-critic/go-critic.github.io/pull/20

ci,docs: autogenerate docs (#1016)

---

checkers/rules/rules.go
checkers/rulesdata/rulesdata.go

Was merged too early and can be better, so better to delete for now (+test doc autogen feature 😉 )
Fixes #1350

checkers: drop sloppyTestFuncName

---

checkers/testdata/unlambda/negative_tests.go
checkers/testdata/unlambda/positive_tests.go
checkers/unlambda_checker.go

Count args of CallExpr.
Example: `a(b(1,2))` will be 2, not 1.
fixes #1362

checkers/unlambda: correct calculation amount args.

---

README.md

This PR updates the installation instructions in the README. There is no need to include information about `GO111MODULE` when using modern Go versions.

docs: simplify install instructions via go install

---

checkers/rules/rules.go
checkers/rulesdata/rulesdata.go

It's more a diagnostic check rather than style. First to cases are always const and 3rd is always non-zero which sounds like a diagnostic thing.
Touches `emptyStringTest` a bit.

checkers/sloppyLen: make it diagnostic check

---

docs/overview.md

This PR escapes `<all>` to fix the broken ruleguard's description on the [site](https://go-critic.com/overview.html#ruleguard):

docs: fix ruleguard parameters description

---

checkers/commentFormatting_checker.go
checkers/testdata/commentFormatting/negative_tests.go

For editor documentation, see:
- https://www.jetbrains.com/help/go/code-folding-settings.html#fold-by-default-section
- https://code.visualstudio.com/docs/editor/codebasics#_folding

checkers/commentFormatting: exclude GoLand and VSCode custom folding regions

---

checkers/analyzer/analyzer.go
checkers/analyzer/run.go

There are currently several concurrency issues with the analyzer:
1. `ctx.SetFileInfo` and `c.Check` can be called concurrently. However, go-critic does not support multiple operations on the same context at once.
2. This issue also means that checkers may be called with a context containing the wrong file, because the checker being run in a goroutine may not be complete before `ctx.SetFileInfo` is called for the next file.
3. The same checker is called multiple times in parallel. This is not supported by go-critic, because checkers rely on non-synchronized local state.
It is also worth noting that these issues currently exist even if the `concurrency` flag is set to 1. This is because registering files and running checkers are still executed in parallel, even when concurrency is …

  checkers/analyzer: remove concurrency from `go/analysis` analyzer

---

CONTRIBUTING.md
README.md
tools/tools.go

The Go wiki on GitHub has migrated to go.dev [#61940](https://go.dev/issues/61940).

docs: fix links to Go wiki

---

checkers/rules/precompile.go
checkers/testdata/_integration/ruleguard-glob/rules1.go
checkers/testdata/_integration/ruleguard-glob/rules2.go
checkers/testdata/_integration/ruleguard-multi/rules1.go
checkers/testdata/_integration/ruleguard-multi/rules2.go
checkers/testdata/_integration/ruleguard/rules.go
checkers/testdata/hugeParam/negative_tests_go118.go
checkers/testdata/newDeref/negative_tests118.go
checkers/testdata/paramTypeCombine/negative_tests_go118.go
checkers/testdata/paramTypeCombine/positive_tests_go118.go
checkers/testdata/typeDefFirst/negative_tests_go118.go
checkers/testdata/typeDefFirst/positive_tests_go118.go
tools/tools.go

This PR removes outdated in Go 1.18 `// +build` comments. According to the https://pkg.go.dev/cmd/go#hdr-Build_constraints:
> Go versions 1.16 and earlier used a different syntax for build constraints, with a "// +build" prefix. The gofmt command will add an equivalent //go:build constraint when encountering the older syntax.

checkers: remove outdated build constraint

---

.golangci.yml
Makefile
checkers/caseOrder_checker.go
checkers/internal/astwalk/walk_handler.go
checkers/ruleguard_checker.go
cmd/gocritic/check.go
cmd/makedocs/main.go
linter/helpers.go

The PR enables linting via golangci-lint. It was previously disabled in #1360.
Also, this PR upgrades golangci-lint to the latest version v1.59.1, fixes configuration warnings and appeared lint issues.

dev: enable back golangci-lint

---

.golangci.yml
Makefile

- update golangci-lint to v1.60.2 (go1.23 support)
- fix golangci-lint configuration
You will maybe need this update of ruleguard: https://github.com/quasilyte/go-ruleguard/pull/479

chore: fix CI

---

checkers/rangeAppendAll_checker.go
checkers/testdata/rangeAppendAll/negative_tests.go
checkers/testdata/rangeAppendAll/positive_tests.go

This is a bug I discovered during work.
append all its data while range over it is generally not the intended behavior and can lead to duplicate data.
```go
for _, n := range ns {
...
rs = append(rs, n)     // OK
rs = append(rs, ns...) // Bug
...
}
```
I implemented the checker firstly in my repo and use the [go-linter-runner](https://github.com/alingse/go-linter-runner) github  action to scan top 10k Go repos.  This found real bugs, documented in https://github.com/alingse/sundrylint/issues/1

checkers: add rangeAppendAll

---

checkers/hugeParam_checker.go
checkers/rulesdata/rulesdata.go

Hello,
This will fix a panic when you run go critic with hugeParam and scan a function that is named String, but does not return any value.
The document state the Results could be nil, this change will check for the nil before checking the length.
https://pkg.go.dev/go/ast#FuncType
Please let me know if you need me to write a test or fix anything else.
Thank you again for writing this tool!
example code that when ran with `./gocritic check -enable=hugeParam` will panic
```go
package main
type foo struct {}
func (foo) String() {
// Empty
}
func main() {
f := foo{}
f.String()
}
```

checkers/hugeParam: fix: ast.FuncDecl.Type.Results could be nil when checking for String()

---

go.mod
go.sum

This PR fixes the problem with building go-critic on Homebrew/homebrew-core#201070 with Go 1.24. Also, it fixes failing tests.
> go-critic: [test failure](https://github.com/Homebrew/homebrew-core/actions/runs/12321762564/job/34395107957?pr=201070#step:4:392): Minitest::Assertion: Expected /sloppyLen:\ len\(str\)\ <=\ 0\ can\ be\ len\(str\)\ ==\ 0/ to match "internal error: package \"fmt\" without types was imported from \"command-line-arguments\"\n".
```sh
$ go version
go version go1.24.0 darwin/arm64
$ go test ./...
?       github.com/go-critic/go-critic  [no test files]
2025/02/12 14:55:19 internal error: package "bytes" without types was imported from "github.com/go-critic/go-critic/checkers/testdata/argOrder"
FAIL    github.com/go-critic/go-critic/checkers 4.654s
? …
```

deps: bump x/tools to 0.30.0 to support Go 1.24

---

.golangci.yml
checkers/analyzer/run.go
checkers/checkers_test.go
cmd/gocritic/check.go

The PR enables [`copyloopvar`](https://golangci-lint.run/usage/linters/#copyloopvar) and [`usetesting`](https://golangci-lint.run/usage/linters/#usetesting) linters.

dev: enable copyloopvar and usetesting linters

---

checkers/deprecatedComment_checker.go
checkers/testdata/deprecatedComment/negative_tests.go
checkers/testdata/deprecatedComment/positive_tests.go

Deprecation comments need to [be on their own paragraph](https://go.dev/wiki/Deprecated):
> To signal that an identifier should not be used, **add a paragraph** to its doc comment that begins with Deprecated: followed by some information about the deprecation, and a recommendation on what to use instead, if applicable.
Tools like the `go doc` generator and `staticcheck` explicitly [check for `Deprecated: ` only at the beginning of new paragraphs](https://github.com/dominikh/go-tools/blob/a2bad015c062e0d4ffabc65eb948e76acc395f0d/analysis/facts/deprecated/deprecated.go#L39), and it is a common mistake to write code like this (incorrect!):
```go
// Foo does something.
// Deprecated: use Bar instead.
func Foo() {}
```
Instead of the correct:
```go
// Foo does something.
//
// Deprecated: use …
```

[checkers/deprecatedComment] Check that deprecated convention appears in a separate paragraph

---

.golangci.yml
checkers/badRegexp_checker.go

https://golangci-lint.run/usage/linters/#goprintffuncname
We exclude from linting the exported functions `CheckerContext.Warn`, `CheckerContext.WarnWithPos`, `CheckerContext.WarnFixable`, and `CheckerContext.WarnFixableWithPos` because this change would break anyone depending on the `github.com/go-critic/go-critic/linter` package.

dev: enable goprintffuncname linter

---

checkers/dupOption_checker.go
checkers/testdata/dupOption/negative_tests.go
checkers/testdata/dupOption/positive_tests.go

I first implement it in another copyandpaste linter, i found that the `repeat arg` like `math.Max(a, a)` has already added in go-critic,
so i move the left part `repeat option` here, I have check the open golang github repos, the result can be found here https://github.com/alingse/copyandpaste/issues/7 
of cause, this may report some false-positive case like [docker/compose/blob/main/cmd/compose/compose.go#L399-L407](https://github.com/docker/compose/blob/main/cmd/compose/compose.go#L399-L407)

checkers: add dupOption
