go-critic/go-critic

- README.md
- travis.yml
Script steps:
- get latest sources
- check that code is formatted with gofmt
- ensure go vet has no complaints
- run "go test" on all packages (also serves as a build check)
> all: enable travis CI

- CONTRIBUTING.org
> CONTRIBUTING.org: add links to Go pages

- cmd/kfulint/main.go
By default -enable have a value of "all".
Empty string means "disable all".
Otherwise it works like a comma-separated list of
checker names that are enabled.
Updates #35.
> cmd/kfulint: add -enable flag

- cmd/kfulint/testdata/underef/checker_tests.go
> cmd/kfulint: add tests for underef false positives

- README.md
> readme: add project description and quick start

- cmd/kfulint/lint_test.go
- cmd/kfulint/main.go
- cmd/kfulint/testdata/big-copy/checker_tests.go
- lint/big-copy_checker.go
- lint/lint.go
> lint: add big-copy checker v1

- cmd/kfulint/testdata/parenthesis/checker_tests.go
- lint/parenthesis_checker.go
> lint: parenthesis suggests to simplify size expressions inside array types

- cmd/kfulint/lint_test.go
- cmd/kfulint/testdata/long-chain/checker_tests.go
- cmd/kfulint/testdata/parenthesis/checker_tests.go
- lint/lint.go
- lint/long-chain_checker.go
> lint: long chain expression checker v1

- cmd/kfulint/lint_test.go
- cmd/kfulint/main.go
- cmd/kfulint/testdata/elseif/checker_tests.go
- lint/elseif_checker.go
> lint: add elseif checker v1

- cmd/kfulint/lint_test.go
- cmd/kfulint/testdata/switchif/checker_tests.go
- lint/lint.go
- lint/switchif_checker.go
> lint: add switch -> if suggestions for 1-case statements

- cmd/kfulint/testdata/param-duplication/checker_tests.go
- lint/param-duplication_checker.go
> lint/param-duplication_checker.go improve suggestions 

- .gometalinter.json
- cmd/kfulint/lint_test.go
- cmd/kfulint/main.go
- cmd/kfulint/testdata/big-copy/checker_tests.go
- cmd/kfulint/testdata/elseif/checker_tests.go
- cmd/kfulint/testdata/long-chain/checker_tests.go
- cmd/kfulint/testdata/param-duplication/checker_tests.go
- cmd/kfulint/testdata/param-name/checker_tests.go
- cmd/kfulint/testdata/parenthesis/checker_tests.go
- cmd/kfulint/testdata/switchif/checker_tests.go
- cmd/kfulint/testdata/type-guard/checker_tests.go
- cmd/kfulint/testdata/underef/checker_tests.go
- lint/big-copy_checker.go
- lint/elseif_checker.go
- lint/lint.go
- lint/long-chain_checker.go
- lint/param-duplication_checker.go
- lint/param-name_checker.go
- lint/parenthesis_checker.go
- lint/switchif_checker.go
- lint/type-guard_checker.go
- lint/underef_checker.go
- lint/util.go
- lint/wrappers.go
> all: re-design checkers

- lint/unslice_checker.go
> lint: minor fixes to PR #114

- docs/checkers/builtin-shadow.md
- lint/builtin-shadow_checker.go
> add builtin shadow checker documentation

- cmd/kfulint/testdata/stddef/checker_tests.go
- lint/lint.go
- lint/stddef_checker.go
> lint: add stddef checker

- cmd/kfulint/testdata/range-expr-copy/checker_tests.go
- lint/big-copy_checker.go
- lint/lint.go
- lint/range-expr-copy_checker.go
- lint/util.go
> lint: add range-expr-copy checker

- docs/checkers/big-copy.md
- docs/checkers/range-expr-copy.md
- docs/checkers/stddef.md
- lint/range-expr-copy_checker.go
- lint/stddef_checker.go
> docs: add 2 new checkers docs + added before/after to big-copy

- docs/overview.md
- docs/templates/overview.md.tmpl
> docs/overview.md: add project description

- docs/checkers/ptr-to-ref-param.md
- docs/overview.md
> docs: add ptr-to-ref-param docs

- README.md
> docs: add usage section

- docs/checkers/type-guard.md
- docs/overview.md
> docs: improve type-guard before+after

- cmd/gocritic/testdata/switch-true/negative_tests.go
- cmd/gocritic/testdata/switch-true/positive_tests.go
- docs/checkers/switch-true.md
- docs/overview.md
- lint/flag-deref_checker.go
- lint/lint.go
- lint/stddef_checker.go
- lint/switch-true_checker.go
- lint/util.go
Does trigger at least 2 times on GOROOT:
math/sinh.go:46: switch true {
net/ip.go:225: switch true {
Updates #21
> lint: add switch-true checker

- cmd/gocritic/testdata/append-combine/negative_tests.go
- cmd/gocritic/testdata/append-combine/positive_tests.go
- docs/checkers/append-combine.md
- docs/overview.md
- lint/append-combine_checker.go
- lint/lint.go
- lint/wrappers.go
> lint: add append-chain checker

- README.md
> docs/README.md: fix typo

- cmd/lintwalk/main.go
> cmd/lintwalk: support sub-projects and arbitrary src roots 

- cmd/criticize/main.go
- cmd/gocritic/check-package_test.go
- cmd/gocritic/main.go
> cmd/gocritic: exit with non-zero status on errors

- cmd/gocritic/testdata/unnamedResult/negative_tests.go
- cmd/gocritic/testdata/unnamedResult/positive_tests.go
- lint/unnamedResult_checker.go
> fix unnamed results panic

- docs/overview.md
- docs/templates/overview.md.tmpl
> cmd/makedocs: remove trailing lines

- lint/unusedParam_checker.go
> lint:unusedParam: make early exit

- docs/overview.md
- docs/templates/overview.md.tmpl
> docs/overview.md.tmpl: summary section is missing from the output

- docs/overview.md
- lint/importShadow_checker.go
> docs: fix importShadow docs

- cmd/criticize/main.go
- cmd/lintwalk/main.go
> all: ability to skip auto generated files

- cmd/gocritic/testdata/paramTypeCombine/negative_tests.go
- cmd/gocritic/testdata/paramTypeCombine/positive_tests.go
- lint/paramTypeCombine_checker.go
> lint: ignore unnamed params in paramTypeCombine

- cmd/gocritic/testdata/importShadow/negative_tests.go
- cmd/gocritic/testdata/importShadow/positive_tests.go
> lint: add tests for importShadow

- cmd/gocritic/testdata/boolOpt/negative_tests.go
- cmd/gocritic/testdata/boolOpt/positive_tests.go
- docs/overview.md
- lint/boolOpt_checker.go
Initial version does not includy any fancy rewrites.
We can add more optimization rules later,
including folding to a constant, if we find it useful.
Fixes #275
> lint: add boolOpt checker

- cmd/gocritic/testdata/dupCase/negative_tests.go
- cmd/gocritic/testdata/dupCase/positive_tests.go
- docs/overview.md
- lint/dupCase_checker.go
Detects duplicated case clauses.
> lint: add dupCase checker

- README.md
I spotted several issues with grammar & punctuation in the ReadMe so I have fixed them here.
> Several grammar & punctuation improvements.

- cmd/gocritic/testdata/typeUnparen/negative_tests.go
- cmd/gocritic/testdata/typeUnparen/positive_tests.go
- lint/internal/astwalk/type_expr_walker.go
> lint: in typeUnparen, handle method exprs properly

- lint/testdata/unnamedResult/negative_tests.go
- lint/testdata/unnamedResult/positive_tests.go
- lint/unnamedResult_checker.go
Now it behaves closely to Go style guide.
Far less false positives.
Fixes #259
> lint: fix unnamedResult false positives

- docs/overview.md
- docs/templates/overview.md.tmpl
> docs/templates/overview: fix extra newline

- docs/overview.md
- lint/nestingReduce_checker.go
- lint/testdata/nestingReduce/negative_tests.go
- lint/testdata/nestingReduce/positive_tests.go
> nestingReduce: add initial implementation

- README.md
> all: fix badge links

- docs/overview.md
- lint/elseif_checker.go
- lint/testdata/elseif/negative_tests.go
- lint/testdata/elseif/positive_tests.go
> lint: add elseif checker

- docs/overview.md
- docs/templates/overview.md.tmpl
> docs/templates/overview: use nerd_face emoji properly

- docs/overview.md
- lint/hugeParam_checker.go
- lint/testdata/_sanity/tests.go
- lint/testdata/hugeParam/negative_tests.go
- lint/testdata/hugeParam/positive_tests.go
> lint: add hugeParam checker

- docs/overview.md
- lint/dupBranchBody_checker.go
- lint/testdata/dupBranchBody/negative_tests.go
- lint/testdata/dupBranchBody/positive_tests.go
> lint: add dupBranchBody checker

- docs/overview.md
- lint/dupSubExpr_checker.go
- lint/testdata/dupSubExpr/negative_tests.go
- lint/testdata/dupSubExpr/positive_tests.go
> lint: add dupSubExpr checker

- lint/indexOnlyLoop_checker.go
- lint/testdata/indexOnlyLoop/negative_tests.go
Added related tests in negative_tests.go.
> lint: fix some false positives of indexOnlyLoop

- lint/all_checkers_test.go
> Inlining finding submatches for a warning

- lint/all_checkers_test.go
> lint: simplify code submitted in #406

- lint/testdata/unnamedResult/positive_tests.go
- lint/unnamedResult_checker.go
Looks like a great project! I noticed this warning was a little strangely written, so I decided to stand up this PR to fix it.
Thanks for your time.
> Change 'consider to give name to results'

- README.md
> readme: update coverage badge

- lint/testdata/underef/negative_tests.go
- lint/testdata/underef/positive_tests.go
- lint/underef_checker.go
> lint: fix handling of multi-deref in undered

- docs/overview.md
- lint/testdata/unnecessaryBlock/negative_tests.go
- lint/testdata/unnecessaryBlock/positive_tests.go
- lint/unnecessaryBlock_checker.go
- Mark checker as experimental
- Add more positive and negative tests
- Also match DeclStmt to capture const/var/type decls
- Add indentation to docs text (1 missing tab)
- Generate docs
> lint: suggestions to PR #467

- cmd/lintwalk/main.go
This behavior can be overwritten by "-checkHidden" flag.
By default, I think we expect that it doesn't visit
folders like ".foo" and "_foo".
Fixes #471
> cmd/lintwalk: skip dirs starting with "." or "_" by default

- lint/nestingReduce_checker.go
- lint/testdata/nestingReduce/negative_tests.go
- lint/testdata/nestingReduce/positive_tests.go
> lint: fix nestingReduce false positives

- lint/internal/astwalk/file_walker.go
- lint/internal/astwalk/visitor.go
- lint/internal/astwalk/walker.go
- lint/lint_private.go
> lint/internal/astwalk: add FileVisitor interface and walker

- docs/overview.md
- lint/initClause_checker.go
Also fix trailing period in Summary field.
> lint: generate docs for initClause checker

- docs/overview.md
- lint/floatCompare_checker.go
- lint/testdata/floatCompare/positive_tests.go
> lint,docs: generate floatCompare checker docs

- lint/testdata/unusedParam/positive_tests.go
- lint/unusedParam_checker.go
> [512] Simplify unusedParam warning text

- README.md
> [#474] Add awesome badge to readme

- lint/rangeValCopy_checker.go
> lint: increase rangeValCopy default threshold

- lint/util.go
Return the selected ident itself.
> lint: fix identOf function for selector expr

- docs/overview.md
- lint/assignOp_checker.go
- lint/testdata/assignOp/negative_tests.go
- lint/testdata/assignOp/positive_tests.go
- lint/util.go
> lint: add assignOp checker

- docs/overview.md
- lint/rangeExprCopy_checker.go
See discussion here: https://github.com/ethereum/go-ethereum/pull/17265#issuecomment-410260211
> lint/rangeExprCopy: extend docs with issue link

- lint/emptyFallthrough.go
- lint/testdata/emptyFallthrough/negative_tests.go
- lint/testdata/emptyFallthrough/positive_tests.go
> lint: add emptyFallthrough checker (#522)

- docs/overview.md
- lint/emptyFallthrough_checker.go
- Rename checker file
- Remove trailing period in docs summary
- Use StmtVisitor
- Reduced nesting in Visit method
- Generate docs
> lint: follow-up for PR576

- lint/importPackageName_checker.go
- lint/internal/dummy/dummy.go
- lint/testdata/importPackageName/negative_tests.go
- lint/testdata/importPackageName/positive_tests.go
> lint: add importPackageName checker (#579)

- cmd/criticize/main.go
- cmd/internal/flagparser/flag_parser.go
> all: ignore test files flag

- docs/overview.md
- lint/dupArg_checker.go
- lint/testdata/dupArg/negative_tests.go
- lint/testdata/dupArg/positive_tests.go
> lint: add dupArg checker

- lint/importShadow_checker.go
- lint/lint.go
- lint/lint_private.go
- lint/testdata/importShadow/positive_tests.go
> lint: use precomputed imports map in importShadow

- lint/lint.go
- lint/lint_private.go
- lint/namedConst_checker.go
- lint/testdata/namedConst/positive_tests.go
> lint: handle renamed imports in namedConst

- lint/sqlRowsClose_checker.go
- lint/testdata/sqlRowsClose/negative_tests.go
> lint/sqlRowsClose: fix close in defer

- lint/busySelect_checker.go
- lint/testdata/busySelect/negative_tests.go
- lint/testdata/busySelect/positive_tests.go
> lint/busySelect: fix chan receive outside of the loop

- lint/yodaStyleExpr_checker.go
> Change method to fix typo

- lint/testdata/importShadow/negative_tests.go
> lint: importShadow negative tests for blank imports

- cmd/criticize/main.go
> cmd/criticize: do check external tests as well

- lint/flagDeref_checker.go
> lint: removed the tailing period from the summary

- docs/overview.md
- lint/flagName_checker.go
- lint/testdata/flagName/negative_tests.go
- lint/testdata/flagName/positive_tests.go
> lint: add flagName checker

- lint/testdata/typeSwitchVar/negative_tests.go
> lint: run gofmt over testdata/typeSwitchVar/negative_tests.go

- lint/elseif_checker.go
- lint/testdata/elseif/negative_tests.go
- lint/testdata/elseif/positive_tests.go
> lint: handle inner if stmt else branch properly in elseif checker

- lint/sloppyLen_checker.go
> lint: simplify sloppyLen checker with lintpack.AsBinaryExpr

- Gopkg.lock
- Gopkg.toml
- cmd/criticize/main.go
- lint/all_checkers_test.go
> cmd,lint: use go/packages instead of loader

- lint/sqlRowsClose_checker.go
> lint: replace make([]T, 0) slice init to []T{}

- lint/appendCombine_checker.go
- lint/boolExprSimplify_checker.go
- lint/emptyFmt_checker.go
- lint/flagName_checker.go
- lint/indexAlloc_checker.go
- lint/internal/lintutil/coerce.go
- lint/methodExprCall_checker.go
- lint/sloppyLen_checker.go
- lint/underef_checker.go
- lint/unlambda_checker.go
> lint: replace lint/internal/lintutil coerce.go with astcast package

- checkers/internal/lintutil/astfind.go
- checkers/typeSwitchVar_checker.go
- checkers/typeUnparen_checker.go
- checkers/unlabelStmt_checker.go
- checkers/utils.go
> checkers: move ast find funcs to lintutil pkg

- checkers/testdata/unlambda/negative_tests.go
- checkers/testdata/unlambda/positive_tests.go
- checkers/unlambda_checker.go
Check that all N arguments matched.
Fixes #716
> checkers: fix unlambda false positive for unnamed args

- .golangci.yml
> all: enable megacheck

- checkers/badCond_checker.go
- checkers/testdata/badCond/positive_tests.go
> checkers: ignore parenthesis in badCond inspection

- checkers/testdata/_integration/check_main_only/linttest.golden
- checkers/testdata/_integration/check_main_only/main.go
- checkers/testdata/weakCond/negative_tests.go
- checkers/testdata/weakCond/positive_tests.go
- checkers/weakCond_checker.go
> checkers: add weakCond checker

- checkers/unslice_checker.go
- checkers/weakCond_checker.go
> checkers: apply paramTypeCombine suggestions

- checkers/docStub_checker.go
- checkers/testdata/docStub/negative_tests.go
- checkers/testdata/docStub/positive_tests.go
> checkers: make docStub more reliable

- checkers/exitAfterDefer_checker.go
- checkers/testdata/_integration/check_main_only/linttest.golden
- checkers/testdata/_integration/check_main_only/main.go
- checkers/testdata/exitAfterDefer/negative_tests.go
- checkers/testdata/exitAfterDefer/positive_tests.go
> checkers: add exitAfterDefer checker

- Makefile
- checkers/unnamedResult_checker.go
> make: add go-consistent to CI checks list

- checkers/builtinShadow_checker.go
- checkers/testdata/unlambda/negative_tests.go
- checkers/unlambda_checker.go
- checkers/utils.go
> checkers: fix unlambda handling of builtins

- checkers/boolExprSimplify_checker.go
- checkers/testdata/boolExprSimplify/positive_tests.go
> checker: handle lambdas properly in boolExprSimplify

- checkers/boolExprSimplify_checker.go
- checkers/testdata/boolExprSimplify/negative_tests.go
- checkers/testdata/boolExprSimplify/positive_tests.go
New patterns:
`x <= y-1` => `x < y`
`x+1 <= y` => `x < y`
`x > y-1` => `x >= y`
`x+1 > y` => `x >= y`
`x >= y+1` => `x > y`
`x-1 >= y` => `x > y`
`x < y+1` => `x <= y`
`x-1 < y` => `x <= y`
Updates #616
> checkers: teach boolExprSimplify a few new tricks

- checkers/deprecatedComment_checker.go
- checkers/testdata/deprecatedComment/negative_tests.go
- checkers/testdata/deprecatedComment/positive_tests.go
> checkers: recognize NOTE pattern in deprecatedComment

- LICENSE
Signed-off-by: Atul Bhosale <atul1bhosale@gmail.com>
> Update copyright notice to 2019

- checkers/stringXbytes_checker.go
> checkers: make stringXbytes more linear

- checkers/deprecatedComment_checker.go
- checkers/testdata/deprecatedComment/positive_tests.go
Add a new pattern for deprecatedComment checker
Fixes #723
> checkers: add Depreacted typo pattern

- Makefile
- checkers/testdata/_integration/check_comments/autogen4.go
> ci: enable integration tests

- checkers/argOrder_checker.go
- checkers/testdata/_integration/check_main_only/linttest.golden
- checkers/testdata/_integration/check_main_only/main.go
- checkers/testdata/argOrder/negative_tests.go
- checkers/testdata/argOrder/positive_tests.go
> checkers: add argOrder checker

- checkers/dupArg_checker.go
- checkers/testdata/dupArg/positive_tests.go
> checkers: add math.Max and math.Min to dupArg

- checkers/checkers_test.go
- checkers/hexLiteral_checker.go
Don't permit empty summary or param docs.
> checkers: add checkers info fields test

- cmd/makedocs/main.go
- docs/overview.md
- docs/templates/checker_tr.partial.tmpl
- docs/templates/overview.md.tmpl
Split table into 3 categories and add
enabled/disabled by default info.
> cmd/makedocs: add enabled/disabled by default info

- checkers/flagName_checker.go
New way to detect stdlib packages.
> checkers: simplify flagName

- checkers/octalLiteral_checker.go
- checkers/testdata/octalLiteral/negative_tests.go
- checkers/testdata/octalLiteral/positive_tests.go
> checkers: add octalLiteral checker

- cmd/makedocs/main.go
- docs/overview.md
- docs/templates/checker.partial.tmpl
- docs/templates/overview.md.tmpl
> cmd/makedocs: add checker param docs

- checkers/testdata/typeUnparen/positive_tests.go
> checkers: add make((T)) test for typeUnparen

- checkers/internal/lintutil/zero_value.go
https://github.com/go-critic/go-critic/pull/806#discussion_r257491547
> Add default branch in switch

- Makefile
Based on comment https://github.com/go-critic/go-critic/issues/812#issuecomment-468229965
> Makefile: remove go get -u

- Makefile
- go.mod
- go.sum
- tools.go
As it says on the tin. Fix for #810.
> Remove erroneously added submodule

- tools.go
This will help us to remember why this file is there
and how this pattern is called.
> tools.go: add a note about "dependency tracking"

- checkers/testdata/wrapperFunc/negative_tests.go
- checkers/testdata/wrapperFunc/positive_tests.go
- checkers/wrapperFunc_checker.go
> checkers: suggest buf.Reset() instead of buf.Truncate(0)

- Makefile
- go.mod
- go.sum
As per https://github.com/go-critic/go-critic/pull/813#issuecomment-468242697.
> Add CI check to keep 'go.mod' clean

- README.md
> readme: specify linter.version argument

- checkers/badCall_checker.go
- checkers/testdata/_integration/check_main_only/linttest.golden
- checkers/testdata/_integration/check_main_only/main.go
- checkers/testdata/badCall/negative_tests.go
- checkers/testdata/badCall/positive_tests.go
> checkers: add badCall checker

- docs/overview.md
Include recently added checkers into the docs.
> docs: re-generate overview from checkers again

- checkers/assignOp_checker.go
- checkers/testdata/assignOp/positive_tests.go
> checkers: suggest x++ instead of x += 1

- checkers/commentedOutCode_checker.go
- checkers/testdata/commentedOutCode/positive_tests.go
> lint: commentedOutCode false negative on multi-statements

- checkers/testdata/_integration/cgo/linttest.params
- checkers/testdata/_integration/cgo/main.go
> checkers: add integration tests with cgo for dupImports

- checkers/testdata/yodaStyleExpr/negative_tests.go
- checkers/testdata/yodaStyleExpr/positive_tests.go
- checkers/yodaStyleExpr_checker.go
> checkers: extend yodaStyleExpr supported ops list

- checkers/checkers.go
> checkers: fix collection URL

- checkers/testdata/unlambda/negative_tests.go
- checkers/unlambda_checker.go
> checkers: don't warn on var funcs

- Makefile
Same as https://github.com/go-critic/go-critic/pull/890
> makefile: correct linter.version argument

- README.md
Also, fix minor typos in other examples.
> readme: add -enableAll example

- checkers/deferUnlambda_checker.go
- checkers/testdata/_integration/check_main_only/linttest.golden
- checkers/testdata/_integration/check_main_only/main.go
- checkers/testdata/deferUnlambda/negative_tests.go
- checkers/testdata/deferUnlambda/positive_tests.go
> checkers: add deferUnlambda checker

- checkers/commentFormatting_checker.go
- checkers/testdata/commentFormatting/negative_tests.go
> checkers: ignore //export comments in commentFormatting

- README.md
> readme: reduce logo size a bit

- .golangci.yml
resolve #948
have to remove previous #949 mr to reduce unnecessary commits.
> .golangci.yml: Enable govet in golangci config (#948)

- checkers/typeDefFirst_checker.go
> checkers: minor refactoring of typeDefFirst checker

- .golangci.yml
> .golangci.yml: make it beautiful

- checkers/caseOrder_checker.go
- framework/linter/lintpack.go
- framework/linttest/linttest.go
> framework/linttest: add missing NeedName flag

- checkers/argOrder_checker.go
- checkers/testdata/argOrder/negative_tests.go
> checkers: make argOrder checker more conservative

- framework/linttest/linttest.go
For every checker, add a `$checker/debug` test that runs
checker on `checkers/testdata/$checker/debug.go` file only.
When debugging, this command can be used:
go test -v -run /$checker/debug ./checkers
When doing a simple -run /$checker, all 3 test groups are executed:
1. /$checker/debug
2. /$checker/sanity
3. /$checker
Updates #980
> framework/linttest: add $checker/debug test for debugging

- checkers/commentFormatting_checker.go
- checkers/testdata/commentFormatting/negative_tests.go
- checkers/testdata/commentFormatting/positive_tests.go
> checkers: don't warn on nolint with reason in commentFormatting

- Makefile
- checkers/sortSlice_checker.go
- checkers/whyNoLint_checker.go
- rules.go
> Makefile: run gocritic with -enableAll over our sources

- README.md
- framework/lintmain/internal/check/check.go
Added Security Tag to description and to code. Removed old PR due to issues.
> framework/lintmain: add security tag

- checkers/testdata/unlambda/positive_tests.go
- checkers/unlambda_checker.go
> checkers: fix unlambda panic on variadic func literals

- checkers/testdata/unlambda/negative_tests.go
- checkers/testdata/unlambda/positive_tests.go
- checkers/unlambda_checker.go
> checkes: fix unlambda false positive on ptr vars

- checkers/stringXbytes_checker.go
- checkers/testdata/stringXbytes/negative_tests.go
> checker: fix stringXbytes

- checkers/ruleguard_checker.go
Add `failOnError` flag to control the ruleguard parser behavior when a gorule file contains a syntax error.
When `failOnError` is set to `false` (default), a ruleguard file that contains at least one syntax error is skipped.
When `failOnError` is set to `true`, a panic occurs if at least one ruleguard file contains a syntax error. 
Previously, the ruleguard parser was returning on the first file parsing error. Additional ruleguard files that hadn't been parsed were ignored. I propose to change that behavior: skip files that contain errors and continue parsing all ruleguard files. This is useful when creating rules that require a new ruleguard grammar, which is not supported yet in the released software, but might be available in a fork.
> Add failOnErrorFlag to cause panic if rule contains an error

- CONTRIBUTING.md
delete dependencies chapter and update telegram links
> update contributing file

- checkers/emptyFallthrough_checker.go
- checkers/testdata/emptyFallthrough/negative_tests.go
> checkers: fix emptyFallthrough false positive on default

- checkers/commentFormatting_checker.go
- checkers/testdata/commentFormatting/line.go
- checkers/testdata/commentFormatting/negative_tests.go
> checkers: commentFormatting: allow `-` in pragma tag names

- checkers/internal/astwalk/type_expr_walker.go
- checkers/testdata/typeUnparen/negative_tests.go
- checkers/testdata/typeUnparen/positive_tests.go
- checkers/typeUnparen_checker.go
> checkers: fix typeUnparen suggestions for chan types

- cmd/makedocs/main.go
- docs/overview.md
- docs/templates/checker.partial.tmpl
- docs/templates/checker_tr.partial.tmpl
- docs/templates/overview.md.tmpl
Refs: https://github.com/go-critic/go-critic.github.io/pull/14
> docs: generate Markdown

- checkers/internal/astwalk/type_expr_walker.go
- checkers/testdata/typeUnparen/negative_tests.go
> checkers: fix typeUnparen for func type literals

- checkers/badCond_checker.go
- checkers/testdata/badCond/positive_tests.go
> checkers: expand supported conditions for badCondition checker

- Makefile
Fixes #976.
Implemented using plain Makefile. It might be a better idea to write a small shell script or go program to avoid using GNU Make-specific hacks.
> dev: added makefile step to generate new checker

- cmd/makedocs/main.go
- docs/overview.md
> docs: update

- docs/overview.md
This PR regenerates documentation.
Follows #1366
> docs: regenerate docs and add badSyncOnceFunc

- cmd/makedocs/main.go
- docs/overview.md
> docs: fix escape

- checkers/badCond_checker.go
- checkers/testdata/badCond/negative_tests.go
- checkers/testdata/badCond/positive_tests.go
Added checks for RHS also, in case of unsafe expression we should not throw errors.
@cristaloleg 
Fixes #1485
> checker/badCond: rhs should be also check for safe expr
